
package de.vsa.ee.unsecure.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.7.redhat-1
 * Tue Mar 04 17:39:09 CET 2014
 * Generated source version: 2.7.7.redhat-1
 */

@XmlRootElement(name = "echoText", namespace = "http://unsecure.ee.vsa.de/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "echoText", namespace = "http://unsecure.ee.vsa.de/")

public class EchoText {

    @XmlElement(name = "text")
    private java.lang.String text;

    public java.lang.String getText() {
        return this.text;
    }

    public void setText(java.lang.String newText)  {
        this.text = newText;
    }

}

