
package de.vsa.ee.unsecure.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.7.redhat-1
 * Tue Mar 04 17:39:09 CET 2014
 * Generated source version: 2.7.7.redhat-1
 */

@XmlRootElement(name = "echoTextResponse", namespace = "http://unsecure.ee.vsa.de/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "echoTextResponse", namespace = "http://unsecure.ee.vsa.de/")

public class EchoTextResponse {

    @XmlElement(name = "return")
    private java.lang.String _return;

    public java.lang.String getReturn() {
        return this._return;
    }

    public void setReturn(java.lang.String new_return)  {
        this._return = new_return;
    }

}

