package de.vsa.ee.unsecure.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.7.redhat-1
 * 2014-03-04T17:44:53.466+01:00
 * Generated source version: 2.7.7.redhat-1
 * 
 */
@WebServiceClient(name = "UnsecureEchoService", 
                  wsdlLocation = "http://localhost:8080/unsecure?wsdl",
                  targetNamespace = "http://unsecure.ee.vsa.de/") 
public class UnsecureEchoService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://unsecure.ee.vsa.de/", "UnsecureEchoService");
    public final static QName UnsecureEchoPort = new QName("http://unsecure.ee.vsa.de/", "UnsecureEchoPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/unsecure?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(UnsecureEchoService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/unsecure?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public UnsecureEchoService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public UnsecureEchoService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UnsecureEchoService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public UnsecureEchoService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public UnsecureEchoService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public UnsecureEchoService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns UnsecureEcho
     */
    @WebEndpoint(name = "UnsecureEchoPort")
    public UnsecureEcho getUnsecureEchoPort() {
        return super.getPort(UnsecureEchoPort, UnsecureEcho.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UnsecureEcho
     */
    @WebEndpoint(name = "UnsecureEchoPort")
    public UnsecureEcho getUnsecureEchoPort(WebServiceFeature... features) {
        return super.getPort(UnsecureEchoPort, UnsecureEcho.class, features);
    }

}
