package de.vsa.ee.unsecure;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.7.redhat-1
 * 2014-03-11T08:39:54.205+01:00
 * Generated source version: 2.7.7.redhat-1
 * 
 */
@WebService(targetNamespace = "http://echo.ee.vsa.de/", name = "Echo")
@XmlSeeAlso({ObjectFactory.class})
public interface Echo {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "echoText", targetNamespace = "http://echo.ee.vsa.de/", className = "de.vsa.ee.unsecure.EchoText")
    @WebMethod
    @ResponseWrapper(localName = "echoTextResponse", targetNamespace = "http://echo.ee.vsa.de/", className = "de.vsa.ee.unsecure.EchoTextResponse")
    public java.lang.String echoText(
        @WebParam(name = "text", targetNamespace = "")
        java.lang.String text
    );
}
